services:
  web_server:
    image: nginx:latest
    container_name: nstu_web_lab
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/ssl
      - ./www:/usr/share/nginx/html
    restart: always
 
  ftp_basic:
    image: fauria/vsftpd
    container_name: nstu_ftp_basic
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=pass
      - PASV_MIN_PORT=21000
      - PASV_MAX_PORT=21010
      - PASV_ADDRESS=127.0.0.1
    volumes:
      - ./ftp/data:/home/vsftpd/ftpuser
    restart: always
    
  ##GUI
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: nstu_ftp_facade
    ports:
      - "8080:80"
    volumes:
      - ./ftp/data:/srv
      - ./ftp/fb_data:/database
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/srv
    restart: always
  
  sftp_secure:
    image: atmoz/sftp
    container_name: nstu_sftp_secure
    ports:
      - "2223:22" # я занял под ssh 2222
    command: ftpuser:pass:1001
    volumes:
      - ./ftp/data:/home/ftpuser/upload
    restart: always

  mail:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mail_server
    hostname: mail.example.local
    domainname: example.local
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/docker-mailserver/ssl/cert.pem
      - SSL_KEY_PATH=/tmp/docker-mailserver/ssl/key.pem
      - ENABLE_SASL_AUTH=1
      - ENABLE_DNSBL=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
    ports:
      - "25:25"
      - "143:143"
      - "993:993"
    volumes:
      - ./mail/config:/tmp/docker-mailserver/
      - ./mail/setup-mail.sh:/usr/local/bin/user-patches.sh:ro
    restart: always

  ssh:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: ssh_server
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=student
      - PASSWORD_ACCESS=false
    volumes:
      - ~/.ssh/id_rsa.pub:/config/id_rsa.pub:ro
      - ./ssh/setup-ssh.sh:/custom-cont-init.d/setup-ssh.sh:ro
    restart: always
